# print("Welcome to python scripting")
# print("We are working with some special characters")
print("Welcome to python scripting.\nWe are working with some special characters")
print("Hello World")
print("Hello \bWorld")
print("Hello \b\bWorld")
print("Hello \b\b\bWorld")
print("Hello \tWorld")
print('Python\'s class')
print("This is a \"python\" class")
print("C:\\Users\\Automation\\Desktop\\PythonProjects\\new")